# Generated by Django 3.0 on 2023-01-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegAPP', '0001_initial'),
        ('DojoReadsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_user', to='LoginAndRegAPP.User'),
        ),
    ]
