# Generated by Django 3.0 on 2023-01-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DojoReadsAPP', '0002_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
        migrations.AddField(
            model_name='authors',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='DojoReadsAPP.authors'),
        ),
    ]
