# Generated by Django 4.1.5 on 2023-01-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoReadsAPP', '0003_auto_20230103_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
